## --- ALL NAVIGATION ITEMS ---

[[main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[main]]
name = "Posts"
identifier = "post"
weight = 200
url = "/post/"

[[main]]
name = "Contact Me"
identifier = "contact"
weight = 300
url = "/contact/"
