# We'll modify it when we push the repository to the
# website we want to switch to.
baseURL = "http://example.org/"
languageCode = "en-us"
name = "gouthamkrishnakv"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
contentDir = "content"